const GREEN_CONSOLE_COLOR = '\x1b[32m'
const BLUE_CONSOLE_COLOR = '\x1b[34m'
const RED_CONSOLE_COLOR = '\x1b[31m'
const YELLOW_CONSOLE_COLOR = '\x1b[33m'
const WHITE_CONSOLE_COLOR = '\x1b[37m'
const CYAN_CONSOLE_COLOR = '\x1b[36m'

const ONE_SECOND_IN_MS = 1000
const TWO_SECONDS_IN_MS = ONE_SECOND_IN_MS * 2
const FOUR_SECONDS_IN_MS = TWO_SECONDS_IN_MS * 2
const SIX_SECONDS_IN_MS = TWO_SECONDS_IN_MS * 3
const EIGHT_SECONDS_IN_MS = FOUR_SECONDS_IN_MS * 2

const ONLY_NUMBERS_REGEX = new RegExp('^[0-9]*$');

const COLORS = {
    GREEN_CONSOLE_COLOR,
    BLUE_CONSOLE_COLOR,
    RED_CONSOLE_COLOR,
    YELLOW_CONSOLE_COLOR,
    WHITE_CONSOLE_COLOR,
    CYAN_CONSOLE_COLOR
};

const SECONDS = {
    ONE_SECOND_IN_MS,
    TWO_SECONDS_IN_MS,
    FOUR_SECONDS_IN_MS,
    SIX_SECONDS_IN_MS,
    EIGHT_SECONDS_IN_MS,
};

export {
    COLORS,
    SECONDS,
    ONLY_NUMBERS_REGEX
}